version: '3'
services:
  http:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - script

  script:
    build:
      context: ./script  
    volumes:
      - ./src:/app
    depends_on:
      - data

  data:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password