version: '3'
services:
  http:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - script

  script:
    image: php:7.4-fpm
    volumes:
      - ./src:/app
