version: '3.8'  

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    networks:
      - my_network_3
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/app

  php:
    image: php:7.4-fpm
    container_name: php
    networks:
      - my_network_3
    volumes:
      - ./wordpress:/app

  data:
    image: mariadb
    container_name: data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    networks:
      - my_network_3

networks:
  my_network_3:
    driver: bridge  
